# Generated by Django 5.0.3 on 2024-03-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_demolink_project_githublink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demoLink',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='githubLink',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
